python content_importer.py --file spaced_repetition_quiz.json --type quiz --title "Spaced Repetition Quiz" --topics "learning:spaced_repetition"
python content_importer.py --file active_recall_quiz.json --type quiz --title "Active Recall Quiz" --topics "learning:active_recall"
python content_importer.py --file memory_techniques_quiz.json --type quiz --title "Memory Techniques Quiz" --topics "learning:memory_techniques"
python content_importer.py --file note_taking_quiz.json --type quiz --title "Note-Taking Strategies Quiz" --topics "learning:note_taking"
python content_importer.py --file time_blocking_quiz.json --type quiz --title "Time Blocking Quiz" --topics "productivity:time_blocking"
python content_importer.py --file prioritization_quiz.json --type quiz --title "Prioritization Quiz" --topics "productivity:prioritization"
python content_importer.py --file pomodoro_quiz.json --type quiz --title "Pomodoro Technique Quiz" --topics "productivity:pomodoro_technique"
python content_importer.py --file energy_management_quiz.json --type quiz --title "Energy Management Quiz" --topics "productivity:energy_management"
python content_importer.py --file habit_formation_quiz.json --type quiz --title "Habit Formation Quiz" --topics "self_regulation:habit_formation"
python content_importer.py --file focus_techniques_quiz.json --type quiz --title "Focus Techniques Quiz" --topics "self_regulation:focus_techniques"
python content_importer.py --file mood_tracking_quiz.json --type quiz --title "Mood Tracking Quiz" --topics "self_regulation:mood_tracking"
python content_importer.py --file energy_optimization_quiz.json --type quiz --title "Energy Optimization Quiz" --topics "self_regulation:energy_levels"
python content_importer.py --file effective_practice_quiz.json --type quiz --title "Effective Practice Quiz" --topics "study:effective_practice"
python content_importer.py --file retrieval_practice_quiz.json --type quiz --title "Retrieval Practice Quiz" --topics "study:retrieval_practice"
python content_importer.py --file elaboration_interleaving_quiz.json --type quiz --title "Elaboration & Interleaving Quiz" --topics "study:elaboration,study:interleaving"
